services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        networks:
            - laravel
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_DATABASE: notification_task
            MYSQL_ROOT_PASSWORD: 123456  # Root password set to 123456
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
